// AUTO-GENERATED by scripts/sync_categories.py — DO NOT EDIT BY HAND.
// Source of truth: crawler/categories.py (CATEGORY_DEFS). Run the script to
// regenerate, or `python scripts/sync_categories.py --check` in CI to verify.

export const CATEGORIES = [
  "cloud",
  "llm",
  "llm_api_drop",
  "hosting",
  "domain",
  "tools",
  "student",
  "student_pack",
  "course",
  "coupon",
  "ai_tools",
  "coding_agents",
  "open_source_repo",
  "saas_deal",
  "other",
] as const;
export type Category = (typeof CATEGORIES)[number];

export const OFFER_TYPES = [
  "credit",
  "grant",
  "vps",
  "domain",
  "license",
  "subscription",
  "code",
  "giveaway",
  "other",
] as const;
export type OfferType = (typeof OFFER_TYPES)[number];

export const CATEGORY_COLORS: Record<string, string> = {
  cloud: "#0EA5E9",
  llm: "#8B5CF6",
  llm_api_drop: "#6D28D9",
  hosting: "#F59E0B",
  domain: "#10B981",
  tools: "#6366F1",
  student: "#EC4899",
  student_pack: "#DB2777",
  course: "#14B8A6",
  coupon: "#EF4444",
  ai_tools: "#A855F7",
  coding_agents: "#F97316",
  open_source_repo: "#22C55E",
  saas_deal: "#F59E42",
  other: "#64748B",
};

export const CATEGORY_EMOJIS: Record<string, string> = {
  cloud: "☁️",
  llm: "🧠",
  llm_api_drop: "🔑",
  hosting: "🖥️",
  domain: "🌐",
  tools: "🧰",
  student: "🎓",
  student_pack: "🎒",
  course: "📚",
  coupon: "🏷️",
  ai_tools: "🤖",
  coding_agents: "⚡",
  open_source_repo: "📦",
  saas_deal: "💼",
  other: "✨",
};
