"""
crawler/categories.py — THE single source of truth for the offer taxonomy
==========================================================================
Every category value, its emoji badge, its Discord embed color, and its
prompt-facing description lives here and ONLY here. Anything that needs the
taxonomy — the LLM prompts (verifier), the Discord dispatcher, the schema
CHECK constraint (mirrored, see below), the scheduler assertion, and the
dashboard TypeScript (generated by scripts/sync_categories.py) — derives
from `CATEGORY_DEFS`.

Why this exists: the taxonomy was previously copy-pasted across 8+ places in
three different value sets, guaranteeing drift. This module removes every
duplicate definition.

Note on Postgres: `schema.sql` still hardcodes the CHECK constraint because
Postgres cannot import Python. `tests/test_categories.py` asserts the two
lists stay in sync, so a change here that isn't mirrored in schema.sql fails
the test suite.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CategoryDef:
    """One offer category: its stable key, UI badge, embed color, and doc."""

    key: str
    emoji: str
    color: int          # Discord decimal color (also rendered as hex for the dashboard)
    description: str     # shown to the LLM in the extraction prompt

    @property
    def hex_color(self) -> str:
        return f"#{self.color:06X}"


# --------------------------------------------------------------------------- #
# THE canonical 15-value taxonomy. Order is stable and meaningful (prompt
# ordering, dashboard ordering). Add new categories at the end, before "other".
# --------------------------------------------------------------------------- #
CATEGORY_DEFS: tuple[CategoryDef, ...] = (
    CategoryDef("cloud", "☁️", 0x0EA5E9,
                "AWS/GCP/Azure/DigitalOcean/Hetzner/Fly.io free tiers and credits"),
    CategoryDef("llm", "🧠", 0x8B5CF6,
                "General LLM API free tiers (OpenAI, Anthropic, Groq, Together, etc.)"),
    CategoryDef("llm_api_drop", "🔑", 0x6D28D9,
                "Specifically: unofficial/limited-time free API keys, base URL drops, "
                "\"use my key\" style shares, rate-limited shared endpoints"),
    CategoryDef("hosting", "🖥️", 0xF59E0B,
                "Web hosting, PaaS, static sites (Vercel, Netlify, Railway, Render)"),
    CategoryDef("domain", "🌐", 0x10B981,
                "Free or discounted domain registrations"),
    CategoryDef("tools", "🧰", 0x6366F1,
                "General developer tools, databases, CI/CD, monitoring"),
    CategoryDef("student", "🎓", 0xEC4899,
                "Broad student benefit programs (GitHub Education, JetBrains, etc.)"),
    CategoryDef("student_pack", "🎒", 0xDB2777,
                "Specific curated student pack deals (.edu, .edu.pk, geo-restricted student offers)"),
    CategoryDef("course", "📚", 0x14B8A6,
                "Online courses, bootcamps, certifications"),
    CategoryDef("coupon", "🏷️", 0xEF4444,
                "One-off discount/promo codes for any dev product"),
    CategoryDef("ai_tools", "🤖", 0xA855F7,
                "AI-coding tools with free tiers (Cursor, Lovable, Manus, Windsurf, v0, Bolt, Replit)"),
    CategoryDef("coding_agents", "⚡", 0xF97316,
                "Autonomous coding-agent platforms or IDE plugins with promo tiers"),
    CategoryDef("open_source_repo", "📦", 0x22C55E,
                "Free open-source projects (GitHub repos) that replace paid tools"),
    CategoryDef("saas_deal", "💼", 0xF59E42,
                "SaaS lifetime deals, AppSumo-style offers, \"1 year free\" promotions"),
    CategoryDef("other", "✨", 0x64748B,
                "Anything that doesn't fit above"),
)

# Offer-type axis (small, flat — no per-value metadata needed).
OFFER_TYPES: tuple[str, ...] = (
    "credit", "grant", "vps", "domain", "license",
    "subscription", "code", "giveaway", "other",
)

# --------------------------------------------------------------------------- #
# Derived lookups
# --------------------------------------------------------------------------- #
CATEGORIES: tuple[str, ...] = tuple(d.key for d in CATEGORY_DEFS)
CATEGORY_BY_KEY: dict[str, CategoryDef] = {d.key: d for d in CATEGORY_DEFS}

DEFAULT_CATEGORY = "other"
DEFAULT_OFFER_TYPE = "other"


# --------------------------------------------------------------------------- #
# Coercion / validation
# --------------------------------------------------------------------------- #
def is_valid_category(value: str) -> bool:
    return value in CATEGORY_BY_KEY


def coerce_category(value: str | None) -> str:
    """Normalize an LLM-provided category to a known key, else 'other'."""
    v = (value or DEFAULT_CATEGORY).lower().strip()
    return v if v in CATEGORY_BY_KEY else DEFAULT_CATEGORY


def coerce_offer_type(value: str | None) -> str:
    """Normalize an LLM-provided offer_type to a known value, else 'other'."""
    v = (value or DEFAULT_OFFER_TYPE).lower().strip()
    return v if v in OFFER_TYPES else DEFAULT_OFFER_TYPE


# --------------------------------------------------------------------------- #
# Prompt rendering — both styles derive from the same defs, so single- and
# batch-mode prompts can never drift apart.
# --------------------------------------------------------------------------- #
def category_prompt_block() -> str:
    """Verbose 'key — description' block for the single-item SYSTEM_PROMPT."""
    return "\n".join(f"{d.key:<15} — {d.description}" for d in CATEGORY_DEFS)


def category_prompt_csv() -> str:
    """Compact comma-separated key list for the batch prompt."""
    return ", ".join(CATEGORIES)


def offer_type_prompt_csv() -> str:
    return " | ".join(OFFER_TYPES)
