#!/usr/bin/env python3
"""
scripts/sync_categories.py — generate the dashboard's category taxonomy from
the single Python source of truth (crawler/categories.py).

The Next.js dashboard needs the same category keys, offer types, and colors the
pipeline uses. Rather than hand-maintaining a parallel TypeScript copy (which
drifts — badges.tsx was missing 6 categories), we generate
`dashboard/lib/categories.ts` from `crawler.categories.CATEGORY_DEFS`.

Usage:
    python scripts/sync_categories.py            # write dashboard/lib/categories.ts
    python scripts/sync_categories.py --check     # exit 1 if the file is stale (CI)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from crawler.categories import CATEGORY_DEFS, OFFER_TYPES  # noqa: E402

OUT_PATH = ROOT / "dashboard" / "lib" / "categories.ts"


def _render() -> str:
    cat_keys = ",\n".join(f'  "{d.key}"' for d in CATEGORY_DEFS)
    offer_keys = ",\n".join(f'  "{t}"' for t in OFFER_TYPES)
    colors = "\n".join(f'  {d.key}: "{d.hex_color}",' for d in CATEGORY_DEFS)
    emojis = "\n".join(f'  {d.key}: "{d.emoji}",' for d in CATEGORY_DEFS)
    return f"""// AUTO-GENERATED by scripts/sync_categories.py — DO NOT EDIT BY HAND.
// Source of truth: crawler/categories.py (CATEGORY_DEFS). Run the script to
// regenerate, or `python scripts/sync_categories.py --check` in CI to verify.

export const CATEGORIES = [
{cat_keys},
] as const;
export type Category = (typeof CATEGORIES)[number];

export const OFFER_TYPES = [
{offer_keys},
] as const;
export type OfferType = (typeof OFFER_TYPES)[number];

export const CATEGORY_COLORS: Record<string, string> = {{
{colors}
}};

export const CATEGORY_EMOJIS: Record<string, string> = {{
{emojis}
}};
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync dashboard category taxonomy from Python")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if categories.ts is out of sync (CI mode)")
    args = parser.parse_args()

    rendered = _render()

    if args.check:
        if not OUT_PATH.exists():
            print(f"MISSING: {OUT_PATH} does not exist — run sync_categories.py", file=sys.stderr)
            return 1
        current = OUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"STALE: {OUT_PATH} is out of sync with crawler/categories.py", file=sys.stderr)
            return 1
        print(f"OK: {OUT_PATH.name} is in sync")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(CATEGORY_DEFS)} categories, {len(OFFER_TYPES)} offer types)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
